name: Build and Release

on:
  push:
    branches: [ "main", "master" ]
    tags:
      - 'v*'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:
    name: Build - ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          - name: Windows
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: TL-Rustscan.exe
            name_suffix: .exe
          - name: Linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: TL-Rustscan
            name_suffix: ""
          - name: macOS
            os: macos-13
            target: x86_64-apple-darwin
            bin: TL-Rustscan
            name_suffix: ""

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.platform.target }}

    - name: Install dependencies (Linux)
      if: matrix.platform.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev libssh2-1-dev pkg-config

    - name: Install dependencies (macOS)
      if: matrix.platform.os == 'macos-13'
      run: |
        brew install openssl@3 libssh2 pkg-config

    - name: Build Binary
      run: cargo build --release --target ${{ matrix.platform.target }}

    - name: Rename Binary
      shell: bash
      run: |
        cp target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }} TL-Rustscan-${{ matrix.platform.name }}${{ matrix.platform.name_suffix }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TL-Rustscan-${{ matrix.platform.name }}
        path: TL-Rustscan-${{ matrix.platform.name }}${{ matrix.platform.name_suffix }}

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: TL-Rustscan-${{ matrix.platform.name }}${{ matrix.platform.name_suffix }}
